<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Application;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $applications = [
            [
                'student_name' => 'يوسف محمد الصالح',
                'birth_date' => '2021-03-15',
                'gender' => 'male',
                'parent_name' => 'محمد عبدالله الصالح',
                'parent_phone' => '99887766',
                'parent_email' => 'mohamed.saleh@gmail.com',
                'address' => 'السالمية، قطعة 3، شارع البحر',
                'medical_notes' => 'لا توجد',
                'status' => 'pending',
                'student_photo' => 'sample_photo.jpg',
                'birth_certificate' => 'sample_certificate.pdf',
                'created_at' => now()->subDays(2),
                'updated_at' => now()->subDays(2),
            ],
            [
                'student_name' => 'فاطمة أحمد العنزي',
                'birth_date' => '2020-07-22',
                'gender' => 'female',
                'parent_name' => 'أحمد خالد العنزي',
                'parent_phone' => '97654321',
                'parent_email' => 'ahmed.enezi@gmail.com',
                'address' => 'حولي، شارع تونس، قطعة 2',
                'medical_notes' => 'حساسية من الفول السوداني',
                'status' => 'approved',
                'admin_notes' => 'تم قبول الطالبة، يرجى إحضار المستندات المطلوبة',
                'student_photo' => 'sample_photo.jpg',
                'birth_certificate' => 'sample_certificate.pdf',
                'civil_id' => 'sample_civil_id.pdf',
                'created_at' => now()->subDays(5),
                'updated_at' => now()->subDays(1),
            ],
            [
                'student_name' => 'عمر عبدالعزيز المطيري',
                'birth_date' => '2022-01-10',
                'gender' => 'male',
                'parent_name' => 'عبدالعزيز فهد المطيري',
                'parent_phone' => '96543210',
                'parent_email' => 'abdulaziz.mutairi@gmail.com',
                'address' => 'الجابرية، قطعة 1، شارع المدارس',
                'medical_notes' => null,
                'status' => 'missing_documents',
                'admin_notes' => 'ينقص شهادة الميلاد وصورة البطاقة المدنية',
                'created_at' => now()->subDays(3),
                'updated_at' => now()->subHours(6),
            ],
            [
                'student_name' => 'مريم راشد الخالد',
                'birth_date' => '2021-11-05',
                'gender' => 'female',
                'parent_name' => 'راشد صالح الخالد',
                'parent_phone' => '99776655',
                'parent_email' => 'rashed.khaled@gmail.com',
                'address' => 'مبارك الكبير، أبو فطيرة، شارع 103',
                'medical_notes' => 'ربو خفيف',
                'status' => 'approved',
                'admin_notes' => 'تم القبول، البدء يوم الأحد القادم',
                'student_photo' => 'sample_photo.jpg',
                'created_at' => now()->subWeek(),
                'updated_at' => now()->subDays(2),
            ],
            [
                'student_name' => 'حمد عبدالله الرشيدي',
                'birth_date' => '2019-09-18',
                'gender' => 'male',
                'parent_name' => 'عبدالله حسن الرشيدي',
                'parent_phone' => '98887777',
                'parent_email' => 'abdullah.rashidi@gmail.com',
                'address' => 'الفروانية، الرابية، قطعة 4',
                'medical_notes' => null,
                'status' => 'rejected',
                'admin_notes' => 'عمر الطالب أكبر من الحد المسموح',
                'created_at' => now()->subDays(8),
                'updated_at' => now()->subDays(4),
            ],
            [
                'student_name' => 'نورة ناصر العتيبي',
                'birth_date' => '2021-05-30',
                'gender' => 'female',
                'parent_name' => 'ناصر فيصل العتيبي',
                'parent_phone' => '99665544',
                'parent_email' => 'nasser.otaibi@gmail.com',
                'address' => 'الأحمدي، الفحيحيل، قطعة 8',
                'medical_notes' => 'لا توجد',
                'status' => 'pending',
                'created_at' => now()->subHours(12),
                'updated_at' => now()->subHours(12),
            ],
            [
                'student_name' => 'خالد سليمان الشمري',
                'birth_date' => '2020-12-25',
                'gender' => 'male',
                'parent_name' => 'سليمان محمد الشمري',
                'parent_phone' => '97776666',
                'parent_email' => 'sulaiman.shammari@gmail.com',
                'address' => 'الفروانية، جليب الشيوخ، شارع 80',
                'medical_notes' => 'حساسية من البيض',
                'status' => 'approved',
                'admin_notes' => 'مقبول في الفصل الأزرق',
                'student_photo' => 'sample_photo.jpg',
                'birth_certificate' => 'sample_certificate.pdf',
                'civil_id' => 'sample_civil_id.pdf',
                'created_at' => now()->subDays(10),
                'updated_at' => now()->subDays(6),
            ],
            [
                'student_name' => 'سارة عبدالرحمن العجمي',
                'birth_date' => '2022-04-12',
                'gender' => 'female',
                'parent_name' => 'عبدالرحمن علي العجمي',
                'parent_phone' => '96665555',
                'parent_email' => 'abdulrahman.ajmi@gmail.com',
                'address' => 'الجهراء، القصر، قطعة 2',
                'medical_notes' => null,
                'status' => 'pending',
                'birth_certificate' => 'sample_certificate.pdf',
                'created_at' => now()->subDays(1),
                'updated_at' => now()->subDays(1),
            ],
            [
                'student_name' => 'زياد أحمد الدوسري',
                'birth_date' => '2021-08-08',
                'gender' => 'male',
                'parent_name' => 'أحمد يحيى الدوسري',
                'parent_phone' => '99554433',
                'parent_email' => 'ahmed.dosari@gmail.com',
                'address' => 'السالمية، قطعة 12، شارع المطاعم',
                'medical_notes' => 'يحتاج نظارات طبية',
                'status' => 'missing_documents',
                'admin_notes' => 'ينقص التقرير الطبي',
                'student_photo' => 'sample_photo.jpg',
                'created_at' => now()->subDays(4),
                'updated_at' => now()->subDays(2),
            ],
            [
                'student_name' => 'ريم سعود المنصور',
                'birth_date' => '2020-10-20',
                'gender' => 'female',
                'parent_name' => 'سعود عبدالله المنصور',
                'parent_phone' => '98776655',
                'parent_email' => 'saud.mansour@gmail.com',
                'address' => 'حولي، الشعب، قطعة 6',
                'medical_notes' => 'لا توجد',
                'status' => 'approved',
                'admin_notes' => 'مقبولة، تبدأ الأسبوع القادم',
                'created_at' => now()->subDays(7),
                'updated_at' => now()->subDays(3),
            ],
        ];

        foreach ($applications as $application) {
            Application::create($application);
        }
    }
}
